# Generated by Django 3.1.6 on 2021-04-18 08:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210417_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
        ),
    ]
